name: "Build and push images"

on:
  workflow_dispatch:

jobs:
  Building:
      runs-on: ubuntu-latest
      name: "Build image"
      env:
        DOCKER_ACCOUNTS: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_REPO: ${{ secrets.DOCKER_REPO }}

      steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.0.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.0.0

      - name: Process Docker accounts and push images
        run: |
          # Parse the account information
          IFS=' ' read -ra accounts <<< "${{ env.DOCKER_ACCOUNTS }}"
          
          for account in "${accounts[@]}"; do
            # Split the account string to extract username and password
            username=${account%%::*}
            password=${account##*::}
            
            echo "Processing account: $username"
            
            # Login to DockerHub
            echo "$password" | docker login -u "$username" --password-stdin
            
            if [ $? -eq 0 ]; then
              echo "Successfully logged in as $username"
              
              # Build and push the image
              docker buildx build --platform linux/amd64,linux/arm64 \
                --push \
                --tag "$username/${{ env.DOCKER_REPO }}:latest" .
              
              echo "Image pushed to $username/${{ env.DOCKER_REPO }}:latest"
            else
              echo "Failed to login as $username"
            fi
          done
